// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Xamarin.WebServices.Core.Model
{

    internal class ConceptGroup
    {

        [JsonProperty("tty")]
        public string Tty { get; set; }

        [JsonProperty("conceptProperties")]
        public ConceptProperty[] ConceptProperties { get; set; }
    }

}
