// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Xamarin.WebServices.Core.Model
{

    internal class DrugGroup
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("conceptGroup")]
        public ConceptGroup[] ConceptGroup { get; set; }
    }

}
