//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.WebServicesAsync.Droid.RxNav {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RxNormDBServiceSoapBinding", Namespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxTermInfo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxNode))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxEdge))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxMinimalConcept))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxMatchInfo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxConceptGroup))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RxPropertyConcept))]
    public partial class DBManagerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DBManagerService() {
            this.Url = "http://mor.nlm.nih.gov/axis/services/RxNormDBService";
        }
        
        public DBManagerService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        public void close() {
            this.Invoke("close", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginclose(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("close", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void Endclose(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRxPropertyReturn")]
        public RxPropertyConcept[] getRxProperty(string rxcui, string prop_name) {
            object[] results = this.Invoke("getRxProperty", new object[] {
                        rxcui,
                        prop_name});
            return ((RxPropertyConcept[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRxProperty(string rxcui, string prop_name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRxProperty", new object[] {
                        rxcui,
                        prop_name}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxPropertyConcept[] EndgetRxProperty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxPropertyConcept[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getStrengthReturn")]
        public string getStrength(string rxcui) {
            object[] results = this.Invoke("getStrength", new object[] {
                        rxcui});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetStrength(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getStrength", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetStrength(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("findRxcuiByIdReturn")]
        public string[] findRxcuiById(string idType, string id) {
            object[] results = this.Invoke("findRxcuiById", new object[] {
                        idType,
                        id});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindRxcuiById(string idType, string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findRxcuiById", new object[] {
                        idType,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndfindRxcuiById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="findRxcuiById1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("findRxcuiByIdReturn")]
        public string[] findRxcuiById(string idType, string id, int allSourcesFlag) {
            object[] results = this.Invoke("findRxcuiById1", new object[] {
                        idType,
                        id,
                        allSourcesFlag});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindRxcuiById1(string idType, string id, int allSourcesFlag, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findRxcuiById1", new object[] {
                        idType,
                        id,
                        allSourcesFlag}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndfindRxcuiById1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMultiIngredBrandReturn")]
        public RxConcept[] getMultiIngredBrand(string[] ids) {
            object[] results = this.Invoke("getMultiIngredBrand", new object[] {
                        ids});
            return ((RxConcept[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetMultiIngredBrand(string[] ids, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMultiIngredBrand", new object[] {
                        ids}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxConcept[] EndgetMultiIngredBrand(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxConcept[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRxConceptPropertiesReturn")]
        public RxConcept getRxConceptProperties(string rxcui) {
            object[] results = this.Invoke("getRxConceptProperties", new object[] {
                        rxcui});
            return ((RxConcept)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRxConceptProperties(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRxConceptProperties", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxConcept EndgetRxConceptProperties(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxConcept)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllPropertiesReturn")]
        public RxPropertyConcept[] getAllProperties(string rxcui, string[] propCat) {
            object[] results = this.Invoke("getAllProperties", new object[] {
                        rxcui,
                        propCat});
            return ((RxPropertyConcept[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllProperties(string rxcui, string[] propCat, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllProperties", new object[] {
                        rxcui,
                        propCat}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxPropertyConcept[] EndgetAllProperties(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxPropertyConcept[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getNDCsReturn")]
        public string[] getNDCs(string rxcui) {
            object[] results = this.Invoke("getNDCs", new object[] {
                        rxcui});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetNDCs(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getNDCs", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetNDCs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("filterByPropertyReturn")]
        public string filterByProperty(string rxcui, string prop_name, string[] prop_value) {
            object[] results = this.Invoke("filterByProperty", new object[] {
                        rxcui,
                        prop_name,
                        prop_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfilterByProperty(string rxcui, string prop_name, string[] prop_value, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("filterByProperty", new object[] {
                        rxcui,
                        prop_name,
                        prop_value}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndfilterByProperty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSplSetIdReturn")]
        public string[] getSplSetId(string rxcui) {
            object[] results = this.Invoke("getSplSetId", new object[] {
                        rxcui});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSplSetId(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSplSetId", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSplSetId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getQuantityReturn")]
        public string getQuantity(string rxcui) {
            object[] results = this.Invoke("getQuantity", new object[] {
                        rxcui});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetQuantity(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getQuantity", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetQuantity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUNIIReturn")]
        public string getUNII(string rxcui) {
            object[] results = this.Invoke("getUNII", new object[] {
                        rxcui});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUNII(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUNII", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetUNII(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRelatedByTypeReturn")]
        public RxConceptGroup[] getRelatedByType(string rxcui, string[] termType_list) {
            object[] results = this.Invoke("getRelatedByType", new object[] {
                        rxcui,
                        termType_list});
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelatedByType(string rxcui, string[] termType_list, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelatedByType", new object[] {
                        rxcui,
                        termType_list}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxConceptGroup[] EndgetRelatedByType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRelatedByRelationshipReturn")]
        public RxConceptGroup[] getRelatedByRelationship(string rxcui, string[] rela_list) {
            object[] results = this.Invoke("getRelatedByRelationship", new object[] {
                        rxcui,
                        rela_list});
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelatedByRelationship(string rxcui, string[] rela_list, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelatedByRelationship", new object[] {
                        rxcui,
                        rela_list}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxConceptGroup[] EndgetRelatedByRelationship(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllRelatedInfoReturn")]
        public RxConceptGroup[] getAllRelatedInfo(string rxcui) {
            object[] results = this.Invoke("getAllRelatedInfo", new object[] {
                        rxcui});
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllRelatedInfo(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllRelatedInfo", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxConceptGroup[] EndgetAllRelatedInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("findRxcuiByStringReturn")]
        public string[] findRxcuiByString(string term) {
            object[] results = this.Invoke("findRxcuiByString", new object[] {
                        term});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindRxcuiByString(string term, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findRxcuiByString", new object[] {
                        term}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndfindRxcuiByString(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="findRxcuiByString1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("findRxcuiByStringReturn")]
        public string[] findRxcuiByString(string term, string[] sources, int allSourcesFlag) {
            object[] results = this.Invoke("findRxcuiByString1", new object[] {
                        term,
                        sources,
                        allSourcesFlag});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindRxcuiByString1(string term, string[] sources, int allSourcesFlag, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findRxcuiByString1", new object[] {
                        term,
                        sources,
                        allSourcesFlag}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndfindRxcuiByString1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="findRxcuiByString2")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("findRxcuiByStringReturn")]
        public string[] findRxcuiByString(string term, string[] sources, int allSourcesFlag, int matchType) {
            object[] results = this.Invoke("findRxcuiByString2", new object[] {
                        term,
                        sources,
                        allSourcesFlag,
                        matchType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindRxcuiByString2(string term, string[] sources, int allSourcesFlag, int matchType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findRxcuiByString2", new object[] {
                        term,
                        sources,
                        allSourcesFlag,
                        matchType}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndfindRxcuiByString2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getDrugsReturn")]
        public RxConceptGroup[] getDrugs(string name) {
            object[] results = this.Invoke("getDrugs", new object[] {
                        name});
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDrugs(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDrugs", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxConceptGroup[] EndgetDrugs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxConceptGroup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSourceTypesReturn")]
        public string[] getSourceTypes() {
            object[] results = this.Invoke("getSourceTypes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSourceTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSourceTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSourceTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("approxMatchReturn")]
        public RxMatchInfo[] approxMatch(string term) {
            object[] results = this.Invoke("approxMatch", new object[] {
                        term});
            return ((RxMatchInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginapproxMatch(string term, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("approxMatch", new object[] {
                        term}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxMatchInfo[] EndapproxMatch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxMatchInfo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getApproximateMatchReturn")]
        public RxMatchGroup getApproximateMatch(string term, int ranks, int options) {
            object[] results = this.Invoke("getApproximateMatch", new object[] {
                        term,
                        ranks,
                        options});
            return ((RxMatchGroup)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetApproximateMatch(string term, int ranks, int options, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getApproximateMatch", new object[] {
                        term,
                        ranks,
                        options}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxMatchGroup EndgetApproximateMatch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxMatchGroup)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllConceptsByTTYReturn")]
        public RxMinimalConcept[] getAllConceptsByTTY(string[] ttyList) {
            object[] results = this.Invoke("getAllConceptsByTTY", new object[] {
                        ttyList});
            return ((RxMinimalConcept[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllConceptsByTTY(string[] ttyList, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllConceptsByTTY", new object[] {
                        ttyList}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxMinimalConcept[] EndgetAllConceptsByTTY(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxMinimalConcept[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPropNamesReturn")]
        public string[] getPropNames() {
            object[] results = this.Invoke("getPropNames", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPropNames(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPropNames", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetPropNames(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getTermTypesReturn")]
        public string[] getTermTypes() {
            object[] results = this.Invoke("getTermTypes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTermTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTermTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetTermTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getIdTypesReturn")]
        public string[] getIdTypes() {
            object[] results = this.Invoke("getIdTypes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetIdTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getIdTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetIdTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRelaTypesReturn")]
        public string[] getRelaTypes() {
            object[] results = this.Invoke("getRelaTypes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelaTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelaTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetRelaTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPropCategoriesReturn")]
        public string[] getPropCategories() {
            object[] results = this.Invoke("getPropCategories", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPropCategories(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPropCategories", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetPropCategories(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSpellingSuggestionsReturn")]
        public string[] getSpellingSuggestions(string term) {
            object[] results = this.Invoke("getSpellingSuggestions", new object[] {
                        term});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSpellingSuggestions(string term, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSpellingSuggestions", new object[] {
                        term}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSpellingSuggestions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getDisplayTermsReturn")]
        public string[] getDisplayTerms() {
            object[] results = this.Invoke("getDisplayTerms", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDisplayTerms(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDisplayTerms", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetDisplayTerms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRxcuiStatusReturn")]
        public RxcuiStatus getRxcuiStatus(string rxcui) {
            object[] results = this.Invoke("getRxcuiStatus", new object[] {
                        rxcui});
            return ((RxcuiStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRxcuiStatus(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRxcuiStatus", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxcuiStatus EndgetRxcuiStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxcuiStatus)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getClassHierarchyReturn")]
        public RxTree getClassHierarchy(string rxcui, string sab, string type, int oneLevel) {
            object[] results = this.Invoke("getClassHierarchy", new object[] {
                        rxcui,
                        sab,
                        type,
                        oneLevel});
            return ((RxTree)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetClassHierarchy(string rxcui, string sab, string type, int oneLevel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getClassHierarchy", new object[] {
                        rxcui,
                        sab,
                        type,
                        oneLevel}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxTree EndgetClassHierarchy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxTree)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getProprietaryInformationReturn")]
        public RxTermInfo[] getProprietaryInformation(string rxcui, string[] sources, string proxyTicket) {
            object[] results = this.Invoke("getProprietaryInformation", new object[] {
                        rxcui,
                        sources,
                        proxyTicket});
            return ((RxTermInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProprietaryInformation(string rxcui, string[] sources, string proxyTicket, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProprietaryInformation", new object[] {
                        rxcui,
                        sources,
                        proxyTicket}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxTermInfo[] EndgetProprietaryInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxTermInfo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="getProprietaryInformation1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getProprietaryInformationReturn")]
        public RxTermInfo[] getProprietaryInformation(string rxcui, string[] sources, string proxyTicket, string rxaui) {
            object[] results = this.Invoke("getProprietaryInformation1", new object[] {
                        rxcui,
                        sources,
                        proxyTicket,
                        rxaui});
            return ((RxTermInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProprietaryInformation1(string rxcui, string[] sources, string proxyTicket, string rxaui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProprietaryInformation1", new object[] {
                        rxcui,
                        sources,
                        proxyTicket,
                        rxaui}, callback, asyncState);
        }
        
        /// <remarks/>
        public RxTermInfo[] EndgetProprietaryInformation1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxTermInfo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("findRemappedReturn")]
        public string[] findRemapped(string rxcui) {
            object[] results = this.Invoke("findRemapped", new object[] {
                        rxcui});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindRemapped(string rxcui, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findRemapped", new object[] {
                        rxcui}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndfindRemapped(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://db.rxnorm.nlm.nih.gov", ResponseNamespace="http://mor.nlm.nih.gov/axis/services/RxNormDBService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRxNormVersionReturn")]
        public string getRxNormVersion() {
            object[] results = this.Invoke("getRxNormVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRxNormVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRxNormVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRxNormVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxPropertyConcept {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CATEGORY;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string NAME;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string VALUE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxTermInfo {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CODE;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string RXCUI;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SAB;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string STR;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string TTY;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxTree {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RxEdge[] rxEdge;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RxNode[] rxNode;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxEdge {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ID1;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ID2;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string REL;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxNode {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] ATTR;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string STR;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxcuiStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string date;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] min;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxMinimalConcept {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string RXCUI;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string STR;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string TTY;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxMatchGroup {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comment;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RxMatchInfo[] rxMatchInfo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxMatchInfo {
        
        /// <remarks/>
        public int RANK;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string RXAUI;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string RXCUI;
        
        /// <remarks/>
        public int SCORE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxConceptGroup {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RxConcept[] rxConcept;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class RxConcept {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CUI;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string LAT;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string RXCUI;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string STR;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SUPPRESS;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SY;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string TTY;
    }
}
